scheduler/accounts/urls.py
from django.conf.urls import include, url
from django.views.generic import RedirectView

import views

app_name = 'accounts'
urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url('^profile/$', views.UserDetail.as_view(), name='detail'),
    url('^profile/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='detail'),
    url('^manage/$', RedirectView.as_view(url='users/'), name='manage'),
    url('^manage/users/$', views.ManageUsers.as_view(), name='users'),
    url('^manage/groups/$', views.ManageGroups.as_view(), name='groups'),
]

scheduler/filetree/urls.py
from django.conf.urls import url
from views import BrowseNodesView

app_name = 'filetree'
urlpatterns = [
    url(r'^(?P<path>.*)$', BrowseNodesView.as_view(), name='browse'),
]

scheduler/jobs/urls.py
from django.conf.urls import url

import views

app_name = 'jobs'
urlpatterns = [
    url(r'^jobs/$', views.JobList.as_view(), name='job_list'),
    url(r'^jobs/(?P<pk>[0-9]+)/$', views.JobDetail.as_view(), name='job_detail'),
    url(r'^instances/$', views.JobInstanceList.as_view(), name='instance_list'),
    url(r'^instances/(?P<pk>[0-9]+)/$', views.JobInstanceDetail.as_view(), name='instance_detail'),
]

scheduler/repos/urls.py
from django.conf.urls import url

import views

app_name = 'repos'
urlpatterns = [
    url(r'^$', views.RepoList.as_view(), name='list'),
    url(r'^create/$', views.RepoCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.RepoDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.RepoDelete.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.RepoEdit.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)/sync/$', views.RepoSync.as_view(), name='sync'),
]

scheduler/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import RedirectView

from web.views import ui

# All UIs need the API endpoints
urlpatterns = [
    url('^api/', include('scheduler.api.urls')),
    url('^accounts/', include('scheduler.accounts.urls')),
    url('^timings/', include('scheduler.timings.urls')),
]

if settings.JS_UI:
    urlpatterns += [url('^$', ui)]
else:
    urlpatterns += [
        url('^$', RedirectView.as_view(url='/instances/')),
        url('^browse/', include('scheduler.filetree.urls')),
        url('^directives/', include('scheduler.directives.urls')),
        url('^repos/', include('scheduler.repos.urls')),
        url('^', include('scheduler.jobs.urls'))
    ]

scheduler/web/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load activeurl %}
<html>
    <head>
        <title>Kaizen {% block title %}{% endblock %}</title>
        <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css">-->
        <link rel="stylesheet" href="{% static 'semantic/semantic.min.css' %}">
        <!--<link rel="stylesheet" href="{% static 'calendar.css' %}">-->
        {% block link %}{% endblock link %}
    </head>
    <body>
        {% activeurl parent_tag="a" %}
        <nav class="ui top menu">
            <div class="header item">Kaizen Scheduler</div>

            <a class="item" href="{% url 'jobs:instance_list' %}">Search</a>
            <a class="item" href="{% url 'filetree:browse' path='/' %}">Browse</a>
            <a class="item" href="{% url 'jobs:job_list' %}">Jobs</a>
            <a class="item" href="{% url 'repos:list' %}">Repos</a>
            <a class="item" href="{% url 'directives:list' %}">Directives</a>

            <div class="right menu">
                {% if request.user.is_superuser %}
                <a class="item" href="{% url 'accounts:manage' %}">Accounts</a>
                <a class="item" href="#">Settings</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                {# User is logged in, give them a menu with profile and logout buttons #}
                <div class="ui dropdown icon item">
                    <i class="large user icon"></i>
                    <div class="menu">
                        <a class="item" href="{% url 'accounts:detail' %}">Profile</a>
                        <div class="divider"></div>
                        <a class="item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </div>
                {% else %}
                {# User is not logged in, show them a login button #}
                <a class="item" href="{% url 'accounts:login' %}">Login</a>
                {% endif %}
            </div>
        </nav>
        {% endactiveurl %}

        <main class="ui page container">
        {% block content %}
        {% endblock %}
        </main>

        <!-- Load from static
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.js"></script>
            -->
            <script src="{% static 'jquery/jquery.min.js' %}"></script>
            <script src="{% static 'semantic/semantic.min.js' %}"></script>

            {% block body_script %}{% endblock body_script %}

            <script>
              $(".ui.dropdown").dropdown();
              $(".ui.form").form();
              $('.tabular.menu .item').tab();
              $('.ui.accordion').accordion();
            </script>
    </body>
</html>