scheduler/directives/issue/urls.py
from django.conf.urls import url

import views

app_name = 'issue'
urlpatterns = [
    url(r'^load_rungroup/$', views.IssueLoadRunGroup.as_view(), name='load_rungroup'),

    url(r'^add_job/$', views.IssueAddJob.as_view(), name='add_job'),
    url(r'^load_job/$', views.IssueLoadJob.as_view(), name='load_job'),

    url(r'^kill_ji/$', views.IssueKillJi.as_view(), name='kill_ji'),
    url(r'^run_ji/$', views.IssueRunJi.as_view(), name='run_ji'),
]

scheduler/directives/urls.py
from django.conf.urls import include, url

import views

app_name = 'directives'
urlpatterns = [
    url(r'^$', views.DirectiveList.as_view(), name='list'),
    url(r'^issue/', include('scheduler.directives.issue.urls')),
    url(r'^(?P<pk>[0-9]+)/$', views.DirectiveDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/graph/$', views.vis_graph, name='graph'),
]

scheduler/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import RedirectView

from web.views import ui

# All UIs need the API endpoints
urlpatterns = [
    url('^api/', include('scheduler.api.urls')),
    url('^accounts/', include('scheduler.accounts.urls')),
    url('^timings/', include('scheduler.timings.urls')),
]

if settings.JS_UI:
    urlpatterns += [url('^$', ui)]
else:
    urlpatterns += [
        url('^$', RedirectView.as_view(url='/instances/')),
        url('^browse/', include('scheduler.filetree.urls')),
        url('^directives/', include('scheduler.directives.urls')),
        url('^repos/', include('scheduler.repos.urls')),
        url('^', include('scheduler.jobs.urls'))
    ]

scheduler/directives/models.py
import json

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

from django_celery_results.models import TaskResult
from scheduler.jobs.models import Job, JobInstance
from scheduler.repos.models import Repo
from scheduler.rungroups.models import RunGroupField
import directives
import graph


def require_param(parameter):
    def wrapper(func):
        def func_wrapper(self):
            if parameter not in self.params:
                raise ValidationError("Parameter '%s' required" % parameter)
            return func(self)
        return func_wrapper
    return wrapper


class DirectiveTask(models.Model):
    """ A M2M through table for storing directive tasks """
    directive = models.ForeignKey('Directive')
    result = models.ForeignKey(TaskResult, to_field='task_id', db_constraint=False)

    def __unicode__(self):
        return self.result_id


class Directive(models.Model):
    """ A model representing a directive """

    LOAD_RUNGROUP_DIRECTIVE = 'load_rungroup'

    ADD_JOB_DIRECTIVE = 'add_job'
    LOAD_JOB_DIRECTIVE = 'load_job'

    KILL_JI_DIRECTIVE = 'kill_ji'
    RUN_JI_DIRECTIVE = 'run_ji'

    DIRECTIVES = {
        LOAD_RUNGROUP_DIRECTIVE: 'Load Rungroup',
        ADD_JOB_DIRECTIVE: 'Add Job',
        LOAD_JOB_DIRECTIVE: 'Load Job',
        KILL_JI_DIRECTIVE: 'Kill Job Instance',
        RUN_JI_DIRECTIVE: 'Run Job Instance',
    }

    # Type of directive
    type = models.CharField(max_length=20, choices=DIRECTIVES.items())

    # A directive may operate on many job instance
    job_instances = models.ManyToManyField(JobInstance, blank=True)

    # Each job likely has some parameters as well, store these as generic JSON text
    parameters = models.TextField(default=json.dumps({}))

    # the tasks associated with this directive
    tasks = models.ManyToManyField(TaskResult, through=DirectiveTask)

    # Also store the graph of task completions as JSON
    json_task_graph = models.TextField()

    # When was it issued?
    created_at = models.DateTimeField(auto_now_add=True)

    # And who by?
    created_by = models.ForeignKey(User, related_name='directives')

    def run(self):
        """ Complicated business running directives... """
        taskset = getattr(directives, self.type)(self)
        # Compute the task graph for the directive
        _, _, task_graph = graph.compute_graph(taskset)
        self.json_task_graph = json.dumps(task_graph)
        self.save()

        # Save result objects for every task and add them to the directive
        task_results = [TaskResult(task_id=task_id) for task_id in task_graph]
        TaskResult.objects.bulk_create(task_results)
        d_tasks = [DirectiveTask(directive=self, result=task) for task in task_results]
        DirectiveTask.objects.bulk_create(d_tasks)

        # Finally we can launch the directive
        return taskset.delay()

    @property
    def task_graph(self):
        return json.loads(self.json_task_graph)

    @property
    def result_counts(self):
        """ Return a dictionary of result counts """
        status_counts = self.tasks.values("status").annotate(models.Count('status'))
        return {s['status']: s['status__count'] for s in status_counts}

    @property
    def params(self):
        return json.loads(self.parameters)

    def clean(self):
        """ Make sure we have the right parameters for each type of directive """
        getattr(self, "clean_" + self.type)()

    @property
    def display(self):
        """ Display the parameters nicely for a directive """
        attr = "display_" + self.type

        if hasattr(self, attr):
            return getattr(self, attr)()

        if self.job_instances.count() > 5:
            return "%d job instances" % self.job_instances.count()

        return ', '.join([str(jid) for jid in self.job_instances.values_list('id', flat=True)])

    def display_add_job(self):
        return self.params['name']

    def display_load_rungroup(self):
        return self.params['rungroup']

    def display_load_job(self):
        job = Job.objects.get(id=self.params['job_id'])
        return "%s for %s" % (job, self.params['rungroup'])

    @require_param('name')
    @require_param('definition')
    def clean_add_job(self):
        pass

    @require_param('rungroup')
    def clean_load_rungroup(self):
        pass

    @require_param('rungroup')
    @require_param('job')
    def clean_load_job(self):
        pass

    def __str__(self):
        return "Directive<%d:%s>" % (self.id, self.type)

    class Meta:
        # FIXME
        # ordering = ['-taskset__date_done']
        pass


class AbstractMeta:
    abstract = True
    managed = False


class IssueDirective(models.Model):
    type = models.CharField(max_length=40, choices=Directive.DIRECTIVES.items())
    job_instances = models.ManyToManyField(JobInstance, blank=True)

    @property
    def params(self):
        """ Get the params dictionary for this directive.
        That is every property except type and job_instances. """
        d = {k: v for k, v in self.__dict__.items() if not k.startswith("_")}
        d.pop('type', None)
        d.pop('job_instances', None)
        return d

    class Meta(AbstractMeta):
        pass


class LoadRunGroupDirective(IssueDirective):
    rungroup = RunGroupField()

    class Meta(AbstractMeta):
        pass


class LoadJobDirective(IssueDirective):
    rungroup = RunGroupField()
    job = models.ForeignKey(Job)
    force = models.BooleanField(default=False)

    class Meta(AbstractMeta):
        pass


class AddJobDirective(IssueDirective):
    repo = models.ForeignKey(Repo)
    name = models.CharField(max_length=256)
    definition = models.TextField()

    class Meta(AbstractMeta):
        pass


class KillJiDirective(IssueDirective):
    class Meta(AbstractMeta):
        pass


class RunJiDirective(IssueDirective):
    class Meta(AbstractMeta):
        pass

scheduler/directives/issue/forms.py
from django import forms

from scheduler.directives import models


class IssueDirectiveForm(forms.ModelForm):

    class Meta:
        fields = '__all__'
        widgets = {
            'type': forms.HiddenInput()
        }


class AddJobForm(IssueDirectiveForm):
    description = """
    Create a new adhoc job under the given repo and name.
    Note that you must have execute permissions on the repository in order
    to create a job.
    """

    class Meta(IssueDirectiveForm.Meta):
        model = models.AddJobDirective
        exclude = ['job_instances']


class LoadJobForm(IssueDirectiveForm):
    description = """
    Load the given job into the given rungroup. If an instance of the job already
    exists in that rungroup then the load will be skipped unless the force flag is
    set to true.
    """

    class Meta(IssueDirectiveForm.Meta):
        model = models.LoadJobDirective
        exclude = ['job_instances']
        labels = {
            'force': 'Create a new instance even if one already exists'
        }


class LoadRunGroupForm(IssueDirectiveForm):
    description = """
    Load all jobs matching the given rungroup.
    """

    class Meta(IssueDirectiveForm.Meta):
        model = models.LoadRunGroupDirective
        exclude = ['job_instances']


class KillJiForm(IssueDirectiveForm):
    description = """
    Kill the given job instances
    """

    class Meta(IssueDirectiveForm.Meta):
        model = models.KillJiDirective


class RunJiForm(IssueDirectiveForm):
    description = """
    Run the given job instances igoring any defined dependencies
    """

    class Meta(IssueDirectiveForm.Meta):
        model = models.RunJiDirective

scheduler/directives/issue/views.py
import json

from django.http import HttpResponseRedirect
from django.views import generic

import forms
from scheduler.directives.models import Directive
from scheduler.jobs.models import Job


class IssueDirective(generic.FormView):
    template_name = 'directives/directive_issue.html'
    success_url = '/directives/{id}/'

    def get_initial(self):
        get = {k: v for k, v in self.request.GET.iteritems()}
        get.update({'type': self.directive_type})
        # job_instances is a list, this is a little dirty but until we have
        # another list parameter it'll do.
        get['job_instances'] = self.request.GET.getlist('job_instances', [])
        return get

    def form_valid(self, form):
        """ Create a Directive object and the associated celery task.
        Also convert most of the form into a parameters dictionary
        """
        # Grab the IssueDirective model instance
        issue = form.instance

        # Create a directive then add the M2M relations to JobInstance
        d = Directive.objects.create(
            type=issue.type, parameters=json.dumps(issue.params),
            created_by=self.request.user
        )
        d.job_instances.add(*form.cleaned_data.get('job_instances', []))
        d.run()
        return HttpResponseRedirect(self.success_url.format(**d.__dict__))


class IssueAddJob(IssueDirective):
    form_class = forms.AddJobForm
    directive_type = Directive.ADD_JOB_DIRECTIVE


class IssueLoadRunGroup(IssueDirective):
    form_class = forms.LoadRunGroupForm
    directive_type = Directive.LOAD_RUNGROUP_DIRECTIVE


class IssueLoadJob(IssueDirective):
    form_class = forms.LoadJobForm
    directive_type = Directive.LOAD_JOB_DIRECTIVE

    def get_form(self, **kwargs):
        # FIXME: this really shouldn't be the way to do this
        # Firstly add a custom manager to each model with only permissioned objects
        form = super(IssueLoadJob, self).get_form(**kwargs)
        form.fields['job'].queryset = Job.objects.readable(user=self.request.user)
        return form


class IssueKillJi(IssueDirective):
    form_class = forms.KillJiForm
    directive_type = Directive.KILL_JI_DIRECTIVE


class IssueRunJi(IssueDirective):
    form_class = forms.RunJiForm
    directive_type = Directive.RUN_JI_DIRECTIVE

scheduler/directives/views.py
from django.http import JsonResponse
from django.views import generic

from models import Directive


class DirectiveList(generic.ListView):
    model = Directive


class DirectiveDetail(generic.DetailView):
    model = Directive


def vis_graph(request, pk):
    d = Directive.objects.get(id=pk)

    # Create initial nodes and edges
    nodes = []
    edges = []

    def _node_for_task(task):
        return {
            'id': task.task_id,
            'label': task.task_id,
            'group': task.status
        }

    # Build a dictionary of all tasks
    tasks = {t.task_id: t for t in d.tasks.all()}

    # Now traverse the graph
    for task_id in d.task_graph:
        node = _node_for_task(tasks[task_id])
        nodes.append(node)
        edges.extend([
            {'from': task_id, 'to': to_task_id} for to_task_id in d.task_graph[task_id]
        ])

    return JsonResponse({
        "nodes": nodes,
        "edges": edges
    })

scheduler/directives/templates/directives/directive_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %}- Directives{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'vis/vis.min.css' %}">
{% endblock link %}

{% block content %}
<h1 class="ui left floated header">
    <i class="code icon"></i>
    <div class="content">
        {{ directive.get_type_display }} - {{ directive.display }}
        <div class="sub header">Submitted by {{ directive.created_by.username }} {{ directive.taskset.date_done | naturaltime }}</div>
    </div>
</h1>

<div class="ui clearing divider"></div>

<div class="ui statistics">{% include 'directives/directive_statistics.html' %}</div>

<div class="ui secondary segment" id="directive-graph" style="height: 30em">
    <div class="ui active inverted dimmer">
        <div class="ui loader"></div>
    </div>
</div>

<table class="ui selectable single line table">
    <thead>
        <tr>
            <th>Task ID</th>
            <th>Result</th>
            <th>Errors</th>
            <th>Status</th>
            <th>Finished</td>
        </tr>
    </thead>
    <tbody>
        {% for task in directive.tasks.all %}
        <tr>
            <td>{{ task.task_id }}</td>
            <td>{{ task.result }}</td>
            <td>{% if task.traceback %}<a href="#" onclick="$('#directive_{{ task.task_id }}_errors_modal').modal('show')">Errors</a>{% endif %}</td>
            <td>{{ task.status }}</td>
            <td>{{ task.date_done | naturaltime }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% for task in directive.tasks.all %}
{% if task.traceback %}
<div id="directive_{{ task.task_id }}_errors_modal" class="ui modal">
    <i class="close icon"></i>
    <div class="header">Directive Errors</div>
    <div class="content">
        <div class="ui segment">
            <div class="description"><pre>{{ task.traceback }}</pre></div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

{% endblock content %}

{% block body_script %}
<script src="{% static 'vis/vis.min.js' %}"></script>
<script type="text/javascript">
{% include 'directives/directive_graph.js' %}
</script>
{% endblock body_script %}

scheduler/directives/templates/directives/directive_issue.html
{% extends 'base.html' %}
{% load activeurl %}
{% load humanize %}
{% load semanticui %}

{% block content %}
<h1 class="ui left floated header">
    <i class="code icon"></i>
    <div class="content">
        Issue Directive
        <div class="sub header">Some description</div>
    </div>
</h1>

<div class="ui hidden fitted clearing divider"></div>

{% activeurl parent_tag="a" %}
<div class="ui pointing menu">
    <a class="item" href="{% url 'directives:issue:load_rungroup' %}">Load Rungroup</a>
    <a class="item" href="{% url 'directives:issue:add_job' %}">Add Job</a>
    <a class="item" href="{% url 'directives:issue:load_job' %}">Load Job</a>
    <a class="item" href="{% url 'directives:issue:kill_ji' %}">Kill Job Instance</a>
    <a class="item" href="{% url 'directives:issue:run_ji' %}">Run Job Instance</a>
</div>
{% endactiveurl %}

<div class="ui segment">
    {{ form.description }}
    {{ form.errors }}
    <p>{{ form.non_field_errors }}</p>
    <form class="ui form" method="POST">
        {% csrf_token %}
        {{ form | semanticui }}
        <button class="ui submit primary button">Submit</button>
        <a href="{% url 'directives:list' %}">Cancel</a>
    </form>
</div>

{% endblock content %}

scheduler/directives/templates/directives/directive_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}- Directives{% endblock %}

{% block content %}
<h1 class="ui left floated header">
    <i class="code icon"></i>
    <div class="content">
        Directives
        <div class="sub header">List of all directives (restricted by what?).</div>
    </div>
</h1>

<a class="ui right floated basic button" title="Issue Directive" href="{% url 'directives:issue:load_rungroup' %}"><i class="add icon"></i> Issue Directive</a>

<div class="ui clearing divider"></div>

<div class="ui middle aligned list">
    {% for directive in directive_list %}
    <div class="item">
        <div class="right floated content">
            <div class="ui mini statistics">{% include 'directives/directive_statistics.html' %}</div>
        </div>
        <i class="ui code icon"></i>
        <div class="content">
            <a class="header" href="{% url 'directives:detail' directive.id %}">{{ directive.get_type_display }} - {{ directive.display }}</a>
            <div class="description">Submitted by {{ directive.created_by.username }} {{ directive.taskset.date_done | naturaltime }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

scheduler/directives/templates/directives/directive_statistics.html
{% if directive.result_counts.SUCCESS %}
<div class="green statistic">
    <div class="value">{{ directive.result_counts.SUCCESS }}</div>
    <div class="label">Success</div>
</div>
{% endif %}
{% if directive.result_counts.PENDING %}
<div class="grey statistic">
    <div class="value">{{ directive.result_counts.PENDING }}</div>
    <div class="label">Pending</div>
</div>
{% endif %}
{% if directive.result_counts.RETRY %}
<div class="grey statistic">
    <div class="value">{{ directive.result_counts.RETRY }}</div>
    <div class="label">Retry</div>
</div>
{% endif %}
{% if directive.result_counts.FAILURE %}
<div class="red statistic">
    <div class="value">{{ directive.result_counts.FAILURE }}</div>
    <div class="label">Failed</div>
</div>
{% endif %}