scheduler/jobs/urls.py
from django.conf.urls import url

import views

app_name = 'jobs'
urlpatterns = [
    url(r'^jobs/$', views.JobList.as_view(), name='job_list'),
    url(r'^jobs/(?P<pk>[0-9]+)/$', views.JobDetail.as_view(), name='job_detail'),
    url(r'^instances/$', views.JobInstanceList.as_view(), name='instance_list'),
    url(r'^instances/(?P<pk>[0-9]+)/$', views.JobInstanceDetail.as_view(), name='instance_detail'),
]

scheduler/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import RedirectView

from web.views import ui

# All UIs need the API endpoints
urlpatterns = [
    url('^api/', include('scheduler.api.urls')),
    url('^accounts/', include('scheduler.accounts.urls')),
    url('^timings/', include('scheduler.timings.urls')),
]

if settings.JS_UI:
    urlpatterns += [url('^$', ui)]
else:
    urlpatterns += [
        url('^$', RedirectView.as_view(url='/instances/')),
        url('^browse/', include('scheduler.filetree.urls')),
        url('^directives/', include('scheduler.directives.urls')),
        url('^repos/', include('scheduler.repos.urls')),
        url('^', include('scheduler.jobs.urls'))
    ]

scheduler/jobs/models.py
import json

from django.contrib.contenttypes.fields import GenericRelation
from django.core.urlresolvers import reverse
from django.db import models, transaction

from scheduler.definitions.models import JobDefinition
from scheduler.events.models import Event
from scheduler.filetree.models import Node, NodeQuerySet
from scheduler.repos.models import Repo


class Job(Node):
    """ A Job can be considered the thing that is instantiated when each rungroup loads.
    The Job is associated with a number of definition files and be default is instantiated
    with the last known good file.
    """
    # The repo the job came from, or null if the job is adhoc
    job_repo = models.ForeignKey(Repo, related_name='jobs', blank=True, null=True)

    # Whether or not the Job is active. A job is marked inactive when it is deleted
    # from the repository
    is_active = models.BooleanField(default=True)

    # The definition to use next time we instantiate the job. Users can override this.
    next_definition = models.ForeignKey(JobDefinition, related_name='_job', null=True)

    objects = NodeQuerySet.as_manager()

    @property
    def repo_path(self):
        """ Returns the path relative to the job's repo """
        if self.job_repo:
            return self.path[len(self.job_repo.path) + 1:]
        return self.path

    def bump_instance_numbers(self, rungroup):
        """ Bump the instance number of each of our job instances for the given rungroup.
        TODO: perhaps this should be written on a JobInstance manager, that way it can be applied
        in bulk on any queryset? """
        # FIXME: remove str(rungroup) to rungroup when rungroup becomes a foreign key
        # We need to order by instance DESC to make sure we bump in the right order
        for instance in self.instances.filter(rungroup=str(rungroup)).order_by('-instance'):
            instance.instance += 1
            instance.save()

    def icon(self):
        return 'terminal'

    def link(self):
        return reverse('jobs:job_detail', args=(self.id,))

    class Meta:
        ordering = ('path',)


class JobInstance(models.Model):

    E_STATE = "STATE"
    E_MSG = "MSG"

    # Job that this is an instance of
    job = models.ForeignKey(Job, related_name="instances")

    # Definition the instance is using
    definition = models.ForeignKey(JobDefinition, related_name="instances")

    # Resolved definition job is instantiated with (e.g. rungroup not runperiod)
    # TODO: we could make this a JSONField however it's postgres specific. Once
    # it becomes clear whether or not there is a limited number of fields we might want
    # to search on then we should extract those into columns.
    resolved_definition = models.TextField()

    # Run Group String
    # TODO: use a StubForeignKEy to RunGroup model
    rungroup = models.CharField(max_length=40)

    # Instance number with 0 always being the latest instance. Sounds kinda stupid, but actually if
    # we created new instances with an increasing number then the DB query to get the active (latest)
    # instances gets quite expensive / complicated
    # (see http://stackoverflow.com/questions/586781/postgresql-fetch-the-row-which-has-the-max-value-for-a-column)
    #
    # Instead, if we bump the numbers attached to the old instances then we pay a cost only when we instantiate a
    # new instance (for the same rungroup remember) which is much less frequent than viewing the latest instances.
    instance = models.IntegerField(default=0)

    # We store a reference the router gave us (this may even be the jid) so multiple schedulers can talk to
    # the router letting it assign unique IDs.
    router_id = models.CharField(max_length=128, null=True)

    # The current state of the job
    # TODO: use a states.forms.StateField
    state = models.CharField(max_length=20)

    # The events associated with the job instance
    events = GenericRelation(Event, related_query_name='job_instance')

    @property
    def resolved(self):
        return json.loads(self.resolved_definition)

    @property
    def states(self):
        return self.events.filter(type=self.E_STATE)

    def mark_event(self, event_type, name, data=None):
        Event(content_object=self, type=event_type, name=name, data=json.dumps(data)).save()

    def mark_msg(self, msg):
        self.mark_event(self.E_MSG, name="Message", data=msg)

    @transaction.atomic
    def mark_state(self, state, data=None):
        self.mark_event(self.E_STATE, name=state, data=data)
        self.state = state
        self.save()

    def __unicode__(self):
        return "%s:%s" % (self.job.path, self.rungroup)

    class Meta:
        unique_together = ['job', 'rungroup', 'instance']
        # TODO: this isn't very nice
        get_latest_by = 'id'
        ordering = ['instance']

scheduler/jobs/forms.py
from django import forms
from django.core.validators import RegexValidator

from models import JobInstance


class JobInstanceSearchForm(forms.ModelForm):

    path = forms.CharField(validators=[RegexValidator])

    def __init__(self, *args, **kwargs):
        super(JobInstanceSearchForm, self).__init__(*args, **kwargs)

        # It's a search form, everything should be optional!
        for field in self.fields:
            self.fields[field].required = False

    class Meta:
        model = JobInstance
        fields = ['path', 'rungroup']

scheduler/jobs/views.py
from django.core.exceptions import PermissionDenied
from django.views import generic

from scheduler.filetree.mixins import ReadPermissionMixin
from scheduler.filetree.permissions import filter_readable
from filters import JobInstanceFilter
from forms import JobInstanceSearchForm
from models import Job, JobInstance


class JobList(generic.ListView):
    model = Job

    def get_queryset(self):
        qs = super(JobList, self).get_queryset()
        return qs.readable(user=self.request.user)


class JobDetail(ReadPermissionMixin, generic.DetailView):
    model = Job

    def next_definition_diff(self):
        old = self.object.instances.latest().definition
        new = self.object.next_definition
        return old.diff_to(new)

    def get_context_data(self, **kwargs):
        ctx = super(JobDetail, self).get_context_data(**kwargs)
        ctx['definition_diff'] = self.next_definition_diff()
        return ctx


class JobInstanceList(generic.edit.FormMixin, generic.ListView):
    model = JobInstance
    form_class = JobInstanceSearchForm

    def get_form_kwargs(self):
        kwargs = super(JobInstanceList, self).get_form_kwargs()
        kwargs['data'] = self.request.GET
        return kwargs

    def get_queryset(self):
        qs = super(JobInstanceList, self).get_queryset()
        qs = qs.filter(instance=0)
        qs = filter_readable(qs, user=self.request.user, node_field='job')
        return JobInstanceFilter(self.request.GET, queryset=qs).qs


class JobInstanceDetail(generic.DetailView):
    model = JobInstance
    context_object_name = "ji"

    def get_object(self, *args, **kwargs):
        """ Verify object permissions """
        ji = super(JobInstanceDetail, self).get_object(*args, **kwargs)
        if not ji.job.is_readable(user=self.request.user):
            raise PermissionDenied()
        return ji

scheduler/jobs/templates/jobs/job_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load job_definitions %}

{% block title %}- {{ job.name }}{% endblock %}

{% block body_script %}
<script src="{% static 'chartjs/Chart.bundle.min.js' %}"></script>
<script>
var data = {
  labels: [
    "D20161001", "D20161002", "D20161003", "D20161004",
    "D20161001", "D20161002", "D20161003", "D20161004",
    "D20161001", "D20161002", "D20161003", "D20161004"
  ],
  datasets: [
  {
    backgroundColor: [
      'red', 'green', 'green', 'green',
      'red', 'red', 'green', 'green',
      'green', 'green', 'green', 'green'
    ],
    data: [
      100, 167, 80, 90,
      100, 120, 69, 150,
      90, 60, 80, 95
    ],
  }
  ]
};

var options = {
  legend: { display: false },
  scales: {
    xAxes: [{
      barThickness: 10,
    }]
  }
};

var historyBarChart = new Chart($('#historyBarChart'), {
  type: 'bar',
  data: data,
  options: options
});
</script>
{% endblock body_script %}

{% block content %}
<h1 class="ui left floated header">
  {# Would be nice if this icon could be related to the router type? #}
  <i class="terminal icon"></i>
  <div class="content">
    {{ job.path }}
    <div class="sub header">No description</div>
  </div>
</h1>

<a class="ui right floated basic button {% if not job.next_definition.is_valid %}disabled{% endif %}" href="{% url 'directives:issue:load_job' %}?job={{ job.id }}&rungroup={{ job.next_definition.next_rungroup }}">Load Job</a>

<div class="ui clearing divider"></div>

{# <h2>Job History</h2> #}
<!--<canvas id="historyBarChart" height="40"></canvas> -->

<h2>Next Definition</h2>

{% if job.next_definition.errors %}
<div class="ui icon error message">
  <i class="remove icon"></i>
  <div class="content">
    <div class="header">Invalid job definition!</div>
    <p>We were unable to parse the job definiton file for this job.
    Take a look at the <a href="#" onclick="$('#def_parse_errors_modal').modal('show')">errors</a>.
    </p>
  </div>
</div>
<div id="def_parse_errors_modal" class="ui modal">
  <i class="close icon"></i>
  <div class="header">Definition Parse Errors</div>
  <div class="content">
    <div class="ui segment">
        <div class="description">
            {% for error in job.next_definition.errors %}<pre>{{ error }}</pre>{% endfor %}
        </div>
    </div>
  </div>
</div>
{% endif %}

{% if job.next_definition.warnings %}
<div class="ui icon warning message">
  <i class="remove icon"></i>
  <div class="content">
    <div class="header">Warnings in job definition!</div>
    <p>We encountered some warnings whilst parsing the job definiton file for this job.
    Take a look at the <a href="#" onclick="$('#def_parse_warnings_modal').modal('show')">warnings</a>.
    </p>
  </div>
</div>
<div id="def_parse_warnings_modal" class="ui modal">
  <i class="close icon"></i>
  <div class="header">Definition Parse Warnings</div>
  <div class="content">
    <div class="ui segment">
        <div class="description">
            {% for error in job.next_definition.warnings %}<pre>{{ error }}</pre>{% endfor %}
        </div>
    </div>
  </div>
</div>
{% endif %}

<pre>{{ definition_diff }}</pre>

<h2>Latest Instance</h2>

Launched 5 minutes ago

<h2>Recent Instances</h2>
<table class="ui selectable single line table">
  <thead>
    <tr>
      <th>RunGroup</th>
      <th>Instance</th>
      <th>Version</th>
      <th colspan="2">State</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    {% for ji in job.instances.all %}
    <tr>
      <td>{{ ji.rungroup }}</td>
      <td>{{ ji.instance }}</td>
      <td title="{{ ji.definition.file.version }}"><code>{{ ji.definition.file.version|slice:":7" }}</code>..</td>
      <td>{{ ji.states.latest }}</td>
      <td>{{ ji.states.latest.timestamp | naturaltime }}</td>
      <td><a href="{% url 'jobs:instance_detail' ji.id %}">Job Instance</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

scheduler/jobs/templates/jobs/job_list.html
{% extends 'base.html' %}

{% block title %}- Jobs{% endblock %}

{% block content %}
<h1 class="ui left floated header">
    <i class="terminal icon"></i>
    <div class="content">
        Jobs
        <div class="sub header">From all repositories</div>
    </div>
</h1>

<div class="ui clearing divider"></div>


<table class="ui selectable single line table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Run Period</th>
            <th>Next Run Group</th>
        </tr>
    </thead>
    <tbody>
        {% for job in job_list %}
        <tr {% if job.next_definition.errors %}class="negative" title="Job definition has errors"
            {% elif job.next_definition.warnings %}class="warning" title="Job definition has warnings"{% endif %}>
            <td><a href="{% url 'jobs:job_detail' job.id %}">{{ job.path }}</a></td>
            <td>{{ job.next_definition.runperiod }}</td>
            {% with job.next_definition.next_rungroup as rungroup %}
            <td><a href="{% url 'jobs:instance_list' %}?rungroup={{ rungroup | default_if_none:"" }}">{{ rungroup | default_if_none:"" }}</a></td>
            {% endwith %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

scheduler/jobs/templates/jobs/jobinstance_detail.html
{% extends 'base.html' %}
{% load job_definitions %}
{% load humanize %}

{% block title %}- Instance{% endblock %}

{% block content %}
<h1 class="ui left floated header">
    {# Would be nice if this icon could be related to the router type? #}
    <i class="terminal icon"></i>
    <div class="content">
        {{ ji.job.path }}
        <span class="ui tiny label"><a href="{% url 'jobs:instance_list' %}?rungroup={{ ji.rungroup }}">{{ ji.rungroup }}</a></span>
        <div class="sub header">{{ ji.resolved.description | default:"No description" }}</div>
    </div>
</h1>

<a class="ui right floated basic negative button" href="{% url 'directives:issue:kill_ji' %}?job_instances={{ ji.id }}">Kill</a>
<a class="ui right floated basic button {% if ji.state != "LOADED" %}disabled{% endif %}" href="{% url 'directives:issue:run_ji' %}?job_instances={{ ji.id }}">Run</a>
<a class="ui right floated basic button" href="{% url 'directives:issue:load_job' %}?job={{ ji.job.id }}&rungroup={{ ji.rungroup }}&force=true">Reload</a>

<div class="ui clearing divider"></div>

{# Print out any warnings / errors in the job definition #}
{% if ji.resolved.warnings %}
<div class="ui warning message">
    <div class="content">
        There were <a href="#" onclick="$('#warnings_modal').modal('show')">{{ ji.resolved.warnings|length }} warnings</a> loading the job instance.
    </div>
</div>
<div id="warnings_modal" class="ui modal">
    <div class="header">Job Instance Load Errors</div>
    <div class="content">
        {% for error in ji.resolved.warnings %}
        <div class="ui segment"><pre>{{ error }}</pre></div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% if ji.resolved.errors %}
<div class="ui error message">
    <i class="close icon"></i>
    <div class="content">
        There were <a href="#" onclick="$('#errors_modal').modal('show')">{{ ji.resolved.errors|length }} errors</a> loading the job instance.
    </div>
</div>
<div id="errors_modal" class="ui modal">
    <i class="close icon"></i>
    <div class="header">Job Instance Load Errors</div>
    <div class="content">
        {% for error in ji.resolved.errors %}
        <div class="ui segment"><pre>{{ error }}</pre></div>
        {% endfor %}
    </div>
</div>
{% endif %}

<h2>Logs</h2>

<pre style="background-color: black; color: white; padding: 2px" id="log"></pre>

<h2>States</h2>
<div class="ui feed">
    {% for state in ji.states.all %}
    <div class="event">
        <div class="label"><i class="settings icon"></i></div>
        <div class="content">
            <div class="summary">
                <code>{{ state.name }}</code>
                <div class="date" title="{{ state.timestamp }}">{{ state.timestamp | naturaltime }}</div>
            </div>
            <div class="extra text"><pre>{{ state.pretty_data | default_if_none:"" | urlize }}</pre></div>
        </div>
    </div>
    {% endfor %}
</div>

<h2>Dependencies</h2>
Insert timings / dependencies info here

<h2>Definition</h2>
<div class="ui top attached tabular menu">
    <a class="item active" data-tab="resolved">Resolved</a>
    <a class="item" data-tab="raw">Raw</a>
</div>
<div class="ui bottom attached tab segment active" data-tab="resolved">
    <pre>{{ ji.resolved|pretty_definition | urlize }}</pre>
</div>
<div class="ui bottom attached tab segment" data-tab="raw">
    <pre>{{ ji.definition.file.content | urlize }}</pre>
</div>

{% endblock %}

{% block body_script %}
<script type="text/javascript">
{% include 'jobs/jobinstance_logs.js' %}
</script>
{% endblock body_script %}

scheduler/jobs/templates/jobs/jobinstance_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load semanticui %}

{% block title %}- Instances{% endblock %}

{% block content %}
<h1 class="ui left floated header">
  <i class="terminal icon"></i>
  <div class="content">
    Search Job Instances
    <div class="sub header">Search for job instances by name, repository and run group.</div>
  </div>
</h1>

<div class="ui clearing divider"></div>

<div class="ui accordion">
  <div class="title {% if not request.GET %}active{% endif %}">
    <i class="dropdown icon"></i>
    Filter Form
  </div>
  <div class="content {% if not request.GET %}active{% endif %}">
    <form class="ui form" method="GET">
      {{ form | semanticui }}
      <button class="ui submit primary button">Search</button>
    </form>
  </div>
</div>

<div class="ui divider"></div>

<table class="ui selectable single line table">
  <thead>
    <tr>
      <th>Job</th>
      <th>Run Group</th>
      <th>State</th>
      <th>Last Updated</th>
    </tr>
  </thead>
  <tbody>
    {% for ji in jobinstance_list %}
    <tr {% if 'FAILED' in ji.states.latest.name %}class="negative"{% endif %}>
      <td><a href="{% url 'jobs:instance_detail' ji.id %}">{{ ji.job.path }}</a></td>
      <td>{{ ji.rungroup }}</td>
      <td>{{ ji.states.latest }}</td>
      <td>{{ ji.states.latest.timestamp | naturaltime }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}