scheduler/jobs/urls.py
from django.conf.urls import url

import views

app_name = 'jobs'
urlpatterns = [
    url(r'^jobs/$', views.JobList.as_view(), name='job_list'),
    url(r'^jobs/(?P<pk>[0-9]+)/$', views.JobDetail.as_view(), name='job_detail'),
    url(r'^instances/$', views.JobInstanceList.as_view(), name='instance_list'),
    url(r'^instances/(?P<pk>[0-9]+)/$', views.JobInstanceDetail.as_view(), name='instance_detail'),
]

scheduler/repos/urls.py
from django.conf.urls import url

import views

app_name = 'repos'
urlpatterns = [
    url(r'^$', views.RepoList.as_view(), name='list'),
    url(r'^create/$', views.RepoCreate.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.RepoDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.RepoDelete.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.RepoEdit.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)/sync/$', views.RepoSync.as_view(), name='sync'),
]

scheduler/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import RedirectView

from web.views import ui

# All UIs need the API endpoints
urlpatterns = [
    url('^api/', include('scheduler.api.urls')),
    url('^accounts/', include('scheduler.accounts.urls')),
    url('^timings/', include('scheduler.timings.urls')),
]

if settings.JS_UI:
    urlpatterns += [url('^$', ui)]
else:
    urlpatterns += [
        url('^$', RedirectView.as_view(url='/instances/')),
        url('^browse/', include('scheduler.filetree.urls')),
        url('^directives/', include('scheduler.directives.urls')),
        url('^repos/', include('scheduler.repos.urls')),
        url('^', include('scheduler.jobs.urls'))
    ]

scheduler/repos/models.py
import hashlib
import os

from django.conf import settings
from django.db import models

from django_celery_results.models import TaskResult
from git import GitRepo
from scheduler.filetree.models import Directory, NodeQuerySet


class FilePathField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_length', 256)
        super(FilePathField, self).__init__(*args, **kwargs)


class CommitHashField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_length', 40)
        super(CommitHashField, self).__init__(*args, **kwargs)


class RepoSyncTask(models.Model):
    """ A model to keep track of a repo sync task """
    repo = models.ForeignKey('Repo', related_name='sync_tasks')
    task = models.ForeignKey(TaskResult, to_field='task_id', db_constraint=False)
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def result(self):
        import tasks
        return tasks.sync_repo_result(self.task_id)

    class Meta:
        get_latest_by = 'created_at'


class Repo(Directory):
    """ A repo is a directory node representing a git repository """
    # Description for the repository
    description = models.CharField(max_length=256)

    # URL for how to checkout the repo
    url = models.CharField(max_length=256)

    # Root directory we need to pay attention to
    root = models.CharField(max_length=256)

    # The commitish to checkout (branch, tag or commit)
    commitish = models.CharField(max_length=256, default="master")

    # Last known 'good' commit_hash
    commit_hash = models.CharField(max_length=40, null=True)

    # TODO: will need some more fields to store authentication params
    # For example, need a secret key to POST to the /repo/{id}/sync URL

    objects = NodeQuerySet.as_manager()

    def get_cache_dir(self):
        """ Returns the local cache directory for the given repository.
        The key to use here is the id+url since we allow the commitish
        to change.
        """
        cache_dir = settings.CONFIG['repos']['cache_dir']
        repo_hash = hashlib.sha1(str(self.id) + self.url).hexdigest()
        return os.path.join(cache_dir, repo_hash)

    def get_git_repo(self):
        return GitRepo(self.get_cache_dir(), self.url, self.commitish, self.root)

    def icon(self):
        return "database"

    def __unicode__(self):
        return self.path

scheduler/repos/forms.py
from django import forms

from models import Repo


class RepoForm(forms.ModelForm):

    def clean_path(self):
        """ Make sure the path ends with a slash """
        path = self.cleaned_data['path']
        return path if path.endswith("/") else path + "/"

    class Meta:
        model = Repo
        fields = ['path', 'description', 'url', 'commitish', 'root', 'group']
        labels = {
            'path': 'Mount Path'
        }

scheduler/repos/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from scheduler.filetree.mixins import ReadPermissionMixin, ExecutePermissionMixin

from forms import RepoForm
from models import Repo
import tasks


class RepoList(generic.ListView):
    model = Repo

    def get_queryset(self):
        """ We filter out any repos we don't have read permission on.
        This is arguably incorrect and we may wish to change this in future to
        match unix semantics. That is, to see the existence of a repo we only need
        read permissions on its parent directory """
        qs = super(RepoList, self).get_queryset()
        return qs.readable(user=self.request.user)


class RepoDetail(ReadPermissionMixin, generic.DetailView):
    model = Repo


class RepoSync(ExecutePermissionMixin, generic.DetailView):
    model = Repo

    def get(self, request, *args, **kwargs):
        repo = self.get_object()
        tasks.sync_repo(repo.id)
        return HttpResponseRedirect(reverse('repos:detail', args=(repo.id,)))


class RepoCreate(generic.CreateView):
    model = Repo
    form_class = RepoForm
    success_url = '/repos/{id}'

    def form_valid(self, form):
        """ Save the form setting the owner to the current user """
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save(mkdirs=True)
        return HttpResponseRedirect(self.get_success_url())


class RepoDelete(generic.DeleteView):
    model = Repo

    def get_success_url(self):
        return '/repos/%d' % self.object.id


class RepoEdit(generic.UpdateView):
    model = Repo
    form_class = RepoForm
    template_name = "repos/repo_edit.html"

scheduler/repos/templates/repos/repo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="ui raised red segment">
  <h2 class="ui header">
    Delete {{ repo.name }}?
    <div class="sub header">Are you sure you want to delete {{ repo.name }}?</div>
  </h2>
  <form class="ui form" method="POST">
    {% csrf_token %}
    <button class="ui negative submit button">Yes</button>
    <a class="ui basic button" href="{% url 'repos:detail' repo.id %}">No</a/>
  </form>
</div>
{% endblock content %}

scheduler/repos/templates/repos/repo_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load nodes %}

{% block title %}- {{ repo.name }}{% endblock %}

{% block content %}
<h1 class="ui left floated header">
  <i class="database icon"></i>
  <div class="content">
    {{ repo.path }}
    <div class="sub header">
      {% with repo as node %}{% include 'filetree/permission_labels.html' %}{% endwith %}
      {{ repo.description }}
    </div>
  </div>
</h1>

{% if request.user|can_execute:repo %}
<a class="ui right floated negative basic icon button" title="Delete" href="{% url 'repos:delete' repo.id %}"><i class="trash icon"></i></a>
<a class="ui right floated basic icon button" title="Edit" href="{% url 'repos:edit' repo.id %}"><i class="settings icon"></i></a>
<a class="ui right floated basic button" title="Synchronise" href="{% url 'repos:sync' repo.id %}"><i class="refresh icon"></i> Sync</a>
{% endif %}

<div class="ui clearing divider"></div>

{% with repo.sync_tasks.latest as task %}
{% if task.result.status == 'STARTED' or task.result.status == 'PENDING' %}
<div class="ui icon message">
  <i class="notched circle loading icon"></i>
  <div class="content">
    <div class="header">Just one second...</div>
    <p>We're synchronising your job specs with <code>{{ repo.url }}</code> at commitish <code>{{ repo.commitish }}</code>.
    </p>
  </div>
</div>
{% elif task.result.status == 'SUCCESS' %}
<div class="ui icon success message">
  <i class="checkmark icon"></i>
  <div class="content">
    <div class="header">Sync Succeeded!</div>
    <p>We finished synchronising your job specs to commitish <code>{{ repo.commitish }}</code> {{ task.created_at | naturaltime }}.
    Now running at commit hash <code>{{ repo.commit_hash | slice:":7" }}</code>...
    </p>
  </div>
</div>
{% elif task.result.status == 'FAILURE' %}
<div class="ui icon error message">
  <i class="remove icon"></i>
  <div class="content">
    <div class="header">Sync Failed!</div>
    <p>We failed to synchronise your job specs from <code>{{ repo.url }}</code> {{ task.created_at | naturaltime }}.
    See the <a href="#" onclick="$('#sync_task_errors_modal').modal('show')">stack trace</a>.
    </p>
  </div>
</div>
<div id="sync_task_errors_modal" class="ui modal">
  <i class="close icon"></i>
  <div class="header">Synchronization Errors</div>
  <div class="content">
    <div class="ui segment">
      <div class="header"><pre>{{ task.result.info.exc_type }}</pre></div>
        <div class="description"><pre>{{ task.result.traceback }}</pre></div>
    </div>
  </div>
</div>
{% endif  %}
{% endwith %}


<h2>Jobs</h2>
<table class="ui celled structured striped selectable table">
  <thead>
    <tr>
      <th rowspan="2">Path in Repo</th>
      <th colspan="3">Next Definition</th>
    </tr>
    <tr>
      <th>Run Period</th>
      <th>Version</th>
      <th>Valid</th>
    </tr>
  </thead>
  <tbody>
    {% if repo.jobs.exists %}
    {% for job in repo.jobs.all %}
    <tr {% if not job.next_definition.is_valid %}class="negative"{% endif %}>
      <td><a href="{% url 'jobs:job_detail' job.id %}">{{ job.repo_path }}</a></td>
      <td>{{ job.next_definition.runperiod }}</td>
      <td><code title="{{ job.next_definition.file.version }}">{{ job.next_definition.file.version | slice:":7" }}..</code></td>
      <td>
        {% if job.next_definition.is_valid %}
        <i class="green checkmark icon"></i>
        {% else %}
        <i class="red remove icon"></i>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
    {% else %}
    <tr><td colspan="4" class="disabled center aligned">No Jobs</td></tr>
    {% endif %}
  </tbody>
</table>

<h2>Feed</h2>
<div class="ui feed">
  {% if repo.files.exists %}
  {% for file in repo.files.all %}
  {% with file.definition as def %}
  <div class="event">
    <div class="label">
      <i class="{% if not def.is_valid or def.errors %}red remove{% elif def.warnings %}yellow warning{% else %}green check{% endif %} circle outline icon"></i>
    </div>
    <div class="content">
      <div class="summary">
        {% if def.is_valid %}
        Successfully updated job definition for {{ def.name }}.
        {% else %}
        Failed to parse job definition for {{ def.name }}.
        {% endif %}
        <div class="date">{{ file.created_at | naturaltime }}</div>
      </div>
      <div class="extra text">
        {% if def.is_valid %}Parsed{% else %}Failed to parse{% endif %} definition for {{ def.name }} from version <code title="{{ file.version }}">{{ file.version|slice:":7" }}</code>.. of <code>{{ file.path }}</code>.
      </div>
    </div>
  </div>
  {% endwith %}
  {% endfor %}
  {% else %}
  <p>No activity yet!</p>
  {% endif %}
</div>

{% endblock content %}

scheduler/repos/templates/repos/repo_edit.html
{% extends 'base.html' %}
{% load semanticui %}

{% block content %}
<h1>Modify Repository</h1>
<form class="ui form" method="POST">
    {% csrf_token %}
    {{ form | semanticui }}
    <button class="ui submit primary button">Save</button>
    <a href="{% url 'repos:detail' repo.id %}">Cancel</a>
</form>
{% endblock %}

scheduler/repos/templates/repos/repo_form.html
{% extends 'base.html' %}
{% load semanticui %}

{% block content %}
<h1>Create Repository</h1>
<form class="ui form" method="POST">
    {% csrf_token %}
    {{ form | semanticui }}
    <button class="ui submit primary button">Save</button>
    <a href="/">Cancel</a>
</form>
{% endblock %}

scheduler/repos/templates/repos/repo_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}- Repositories{% endblock %}

{% block content %}
<h1 class="ui left floated header">
  <i class="database icon"></i>
  <div class="content">
    Repositories
    <div class="sub header">List of all repositories you are able to access.</div>
  </div>
</h1>

<a class="ui right floated basic button" title="Create Repository" href="{% url 'repos:create' %}"><i class="add icon"></i> Create Repository</a>

<div class="ui clearing divider"></div>

<div class="ui divided items">
  {% for repo in repo_list %}
  <div class="item">
    <div class="content">
      <a class="header" href="{% url 'repos:detail' repo.id %}">{{ repo.path }}</a>
      <div class="description">{{ repo.description }}</div>
      <div class="extra">
        {% with repo as node %}{% include 'filetree/permission_labels.html' %}{% endwith %}
        <a class="ui label" title="jobs" href="{% url 'repos:detail' repo.id %}">
          <i class="terminal icon"></i> {{ repo.jobs.count }}
        </a>
        {% with repo.sync_tasks.latest as task %}
        {% if task.result.status == 'STARTED' or task.result.status == 'PENDING' %}
        <i title="sync pending" class="notched circle loading icon"></i>
        {% elif task.result.status == 'SUCCESS' %}
        <i title="sync succeeded" class="green checkmark icon"></i>
        {% elif task.result.status == 'FAILURE' %}
        <i title="sync failed" class="red remove icon"></i>
        {% endif %}
        {% endwith %}
        Updated {{ repo.sync_tasks.latest.created_at | naturaltime }}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}